name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore HPPH
      
    - name: Build
      run: dotnet build HPPH --no-restore --configuration Release /p:Version=${{ github.event.inputs.version }}
      
    - name: Test
      run: dotnet test HPPH --no-build --verbosity normal --configuration Release

    - name: List files
      run: tree
      
    - name: Upload Nuget Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: HPPH-Nuget
        path: bin\*.nupkg
        if-no-files-found: error

    - name: Release
      uses: softprops/action-gh-release@v2.0.4
      with:
        tag_name: ${{ github.event.inputs.version }}
        generate_release_notes: true
        files: bin/net8.0/*.dll
                  
    - name: Nuget Push
      run: dotnet nuget push **\*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
      
    - name: Symbols Push
      run: dotnet nuget push **\*.snupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
     
